-- TRIGGERS: update_stock_after_order
-- Generated by DDL Wizard
-- Timestamp: 2025-09-04T14:28:23.595956

CREATE DEFINER=`sstuser`@`%` TRIGGER update_stock_after_order
    AFTER INSERT ON order_items
    FOR EACH ROW
BEGIN
    UPDATE products 
    SET stock_quantity = stock_quantity - NEW.quantity
    WHERE id = NEW.product_id;
END
