-- SEQUENCES: user_id_seq
-- Generated by DDL Wizard
-- Timestamp: 2025-09-04T14:28:23.597030

CREATE SEQUENCE `user_id_seq` start with 1000 minvalue 1000 maxvalue 999999999 increment by 1 cache 10 nocycle ENGINE=InnoDB
