-- PROCEDURES: GetUserOrderHistory
-- Generated by DDL Wizard
-- Timestamp: 2025-09-04T14:28:23.594710

CREATE DEFINER=`sstuser`@`%` PROCEDURE `GetUserOrderHistory`(IN user_id_param INT)
BEGIN
    SELECT 
        o.id as order_id,
        o.order_date,
        o.status,
        o.total_amount,
        COUNT(oi.id) as item_count
    FROM orders o
    LEFT JOIN order_items oi ON o.id = oi.order_id
    WHERE o.user_id = user_id_param
    GROUP BY o.id
    ORDER BY o.order_date DESC;
END
