-- FUNCTIONS: GetUserTotalSpent
-- Generated by DDL Wizard
-- Timestamp: 2025-09-04T14:28:23.595382

CREATE DEFINER=`sstuser`@`%` FUNCTION `GetUserTotalSpent`(user_id_param INT) RETURNS decimal(12,2)
    READS SQL DATA
    DETERMINISTIC
BEGIN
    DECLARE total DECIMAL(12,2) DEFAULT 0.00;
    
    SELECT COALESCE(SUM(total_amount), 0.00) INTO total
    FROM orders 
    WHERE user_id = user_id_param AND status IN ('delivered', 'shipped');
    
    RETURN total;
END
