-- VIEWS: order_summary
-- Generated by DDL Wizard
-- Timestamp: 2025-09-04T14:28:23.593665

CREATE ALGORITHM=UNDEFINED DEFINER=`sstuser`@`%` SQL SECURITY DEFINER VIEW `order_summary` AS select `o`.`id` AS `id`,`o`.`order_date` AS `order_date`,`u`.`username` AS `username`,`u`.`email` AS `email`,`o`.`status` AS `status`,`o`.`total_amount` AS `total_amount`,count(`oi`.`id`) AS `item_count` from ((`orders` `o` join `users` `u` on(`o`.`user_id` = `u`.`id`)) left join `order_items` `oi` on(`o`.`id` = `oi`.`order_id`)) group by `o`.`id`
