-- EVENTS: cleanup_cancelled_orders
-- Generated by DDL Wizard
-- Timestamp: 2025-09-04T14:28:23.596532

CREATE DEFINER=`sstuser`@`%` EVENT `cleanup_cancelled_orders` ON SCHEDULE EVERY 1 DAY STARTS '2025-09-04 14:27:13' ON COMPLETION NOT PRESERVE ENABLE DO DELETE FROM orders 
    WHERE status = 'cancelled' 
    AND order_date < DATE_SUB(NOW(), INTERVAL 30 DAY)
